name: 001-WORKFLOW
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest, windows-latest, macos
    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
      
